const { generateImage } = require('../../lib/imageGenClient');

module.exports = {
    command: ['imagine', 'txt2img', 'aiimage'],
    category: 'ai',
    description: 'Generate gambar dari deskripsi teks menggunakan AI',
    premium: true,
    cooldown: 15,
    limitCost: 3,
    execute: async (msg, { sock, jid, text }) => {
        if (!text) {
            return sock.sendMessage(jid, {
                text: '🎨 Format: *.imagine <deskripsi gambar>*\nContoh: .imagine kucing oranye memakai jubah penyihir, gaya digital art\n\n_Fitur premium karena proses generate gambar cukup berat._'
            }, { quoted: msg });
        }

        await sock.sendMessage(jid, { text: '🎨 Sedang menggambar, mohon tunggu (~10-60 detik)...' }, { quoted: msg });
        await sock.sendMessage(jid, { react: { text: '⏳', key: msg.key } });

        const result = await generateImage(text);

        if (!result.success) {
            await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } });
            return sock.sendMessage(jid, { text: result.error }, { quoted: msg });
        }

        const imageContent = result.url
            ? { url: result.url }
            : Buffer.from(result.base64, 'base64');

        await sock.sendMessage(jid, {
            image: imageContent,
            caption: `🎨 *${text}*\n\n_Generated by AI_`
        }, { quoted: msg });

        await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } });
    }
};
