const fs = require('fs-extra');
const path = require('path');
const { askAI } = require('../../lib/aiClient');
const config = require('../../config/config');

const WEBGEN_SYSTEM_PROMPT = `Kamu adalah generator kode HTML profesional. Tugasmu: buat SATU file HTML lengkap (termasuk CSS di dalam tag <style>, tanpa file eksternal) berdasarkan deskripsi user.

ATURAN KETAT:
- Balas HANYA dengan kode HTML mentah, mulai dari <!DOCTYPE html> sampai </html>
- JANGAN tambahkan penjelasan, markdown code fence (\`\`\`), atau teks lain di luar kode HTML
- Desain harus modern, responsive (mobile-friendly), dan rapi
- Gunakan warna, font, dan layout yang sesuai konteks/tema yang diminta user
- Sertakan minimal: header/nav, satu hero section, beberapa section konten, dan footer
- Semua styling harus inline di tag <style>, jangan pakai CDN eksternal kecuali Google Fonts`;

module.exports = {
    command: ['webgen', 'buatwebsite', 'website'],
    category: 'website',
    description: 'Membuat website landing page sederhana dari deskripsi (AI-generated)',
    premium: true,
    cooldown: 15,
    limitCost: 3,
    execute: async (msg, { sock, jid, text, sender }) => {
        if (!text) {
            return sock.sendMessage(jid, {
                text: `🌐 *WEBSITE GENERATOR*\n\nFormat: *.webgen <deskripsi website>*\n\nContoh:\n.webgen landing page toko baju online nama "Fashionista" dengan warna dominan pink, ada section produk unggulan dan testimoni\n\n_Fitur ini khusus Premium karena membutuhkan proses AI yang lebih berat._`
            }, { quoted: msg });
        }

        await sock.sendMessage(jid, { text: '🔨 Sedang membuat website kamu, mohon tunggu (~30-60 detik)...' }, { quoted: msg });
        await sock.sendMessage(jid, { react: { text: '⏳', key: msg.key } });

        const result = await askAI(`webgen_${sender}`, text, WEBGEN_SYSTEM_PROMPT);

        if (!result.success) {
            await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } });
            return sock.sendMessage(jid, { text: result.error }, { quoted: msg });
        }

        // Bersihkan jika AI tetap menambahkan code fence markdown
        let htmlContent = result.reply.trim();
        htmlContent = htmlContent.replace(/^```html\s*/i, '').replace(/```$/, '').trim();

        if (!htmlContent.toLowerCase().includes('<!doctype') && !htmlContent.toLowerCase().includes('<html')) {
            await sock.sendMessage(jid, { react: { text: '❌', key: msg.key } });
            return sock.sendMessage(jid, { text: '❌ AI tidak menghasilkan HTML yang valid. Coba deskripsi yang lebih spesifik.' }, { quoted: msg });
        }

        const tmpDir = path.join(__dirname, '..', '..', 'tmp');
        await fs.ensureDir(tmpDir);
        const filePath = path.join(tmpDir, `website_${Date.now()}.html`);
        await fs.writeFile(filePath, htmlContent);

        await sock.sendMessage(jid, {
            document: await fs.readFile(filePath),
            fileName: 'website.html',
            mimetype: 'text/html',
            caption: `✅ Website berhasil dibuat!\n\n📌 Cara pakai:\n1. Download file ini\n2. Buka langsung di browser untuk preview\n3. Upload ke hosting (Netlify/Vercel/Github Pages) untuk publish online\n\n_Generated by ${config.botName}_`
        }, { quoted: msg });

        await sock.sendMessage(jid, { react: { text: '✅', key: msg.key } });
        await fs.remove(filePath).catch(() => {});
    }
};
